### ISSUE TITLE
Unreferenced parameter macro does not work for MSVC with NDEBUG (aka Release)

### ISSUE THREAD

**Issue by zahirtezcan-bugs** [Celtoys/Remotery#138] opened 2018-07-12 08:24 UTC
In Remotery.c there is a case for MSVC to fool the compiler: https://github.com/Celtoys/Remotery/blob/858c76eef48aea61da5170f226a742f0de648244/lib/Remotery.c#L143 

Macro uses 'assert' but that totally disappears in Release mode (when NDEBUG is defined). Therefore the compiler still issues warning. I suggest using something like "(i);"

I am using Visual Studio 2017 and compiling for x64.

**Comment by dwilliamson** [comment] 2018-07-12 13:50
Can you give me your command-line please? I can't reproduce the warning:

https://ci.appveyor.com/project/Celtoys/remotery/build/job/88c98rdttr5elgl0

**Comment by zahirtezcan-bugs** [comment] 2018-07-12 20:57
`/permissive- /GS /GL /W4 /Gy /Zc:wchar_t /Zi /Gm- /O2 /sdl /Fd"x64\Release\vc141.pdb" /Zc:inline /fp:precise /D "NDEBUG" /D "_UNICODE" /D "UNICODE" /errorReport:prompt /WX /Zc:forScope /Gd /Oi /MD /std:c++17 /FC /Fa"x64\Release\" /EHsc /nologo /Fo"x64\Release\" /Fp"x64\Release\CppRemoteryTest.pch" /diagnostics:classic `

This was VS2017 Empty Project with "Unicode", "c++17" and "NDEBUG" modifications. The trick is the NDEBUG flag. When it is defined `assert` becomes `((void)0)`

**Comment by Celtoys** [comment] 2018-07-16 12:59
Fixed in 978ce09bdb0448ba5de6e26577cf0332bd5ea047

**Closed by Celtoys** 2018-07-16 12:59 UTC
