### ISSUE TITLE
Connection problems on Win32

### ISSUE THREAD

**Issue by ulanda** [Celtoys/Remotery#36] opened 2015-02-03 10:19 UTC
When Remotery is launched about 25% of the times, starts fine but after a few seconds remotery connection log starts showing connection errors every 2 seconds.
```
[11:08:11] Connecting to ws://127.0.0.1:17815/rmt
[11:08:12] Connection Error 
[11:08:12] Disconnected
[11:08:13] Connecting to ws://127.0.0.1:17815/rmt
[11:08:14] Connection Error 
[11:08:14] Disconnected
[11:08:15] Connecting to ws://127.0.0.1:17815/rmt
[11:08:16] Connection Error 
[11:08:16] Disconnected
[11:08:17] Connecting to ws://127.0.0.1:17815/rmt
[11:08:18] Connection Error 
[11:08:18] Disconnected
[11:08:19] Connecting to ws://127.0.0.1:17815/rmt
[11:08:20] Connection Error 
[11:08:20] Disconnected
```
Looking at the Chome console,  I can see this:
```
WebSocket connection to 'ws://127.0.0.1:17815/rmt' failed: Could not decode a text frame as UTF-8.
WebSocketConnection.js:54 WebSocket connection to 'ws://127.0.0.1:17815/rmt' failed: Invalid frame header
WebSocketConnection.js:54 WebSocket connection to 'ws://127.0.0.1:17815/rmt' failed: Could not decode a text frame as UTF-8.
WebSocketConnection.js:54 WebSocket connection to 'ws://127.0.0.1:17815/rmt' failed: Invalid frame header
WebSocketConnection.js:54 WebSocket connection to 'ws://127.0.0.1:17815/rmt' failed: Could not decode a text frame as UTF-8.
WebSocketConnection.js:54 WebSocket connection to 'ws://127.0.0.1:17815/rmt' failed: Invalid frame header
WebSocketConnection.js:54 WebSocket connection to 'ws://127.0.0.1:17815/rmt' failed: Could not decode a text frame as UTF-8.
WebSocketConnection.js:89 WebSocket connection to 'ws://127.0.0.1:17815/rmt' failed: Invalid frame headerWebSocketConnection.js:89 OnOpen
WebSocketConnection.js:89 WebSocket connection to 'ws://127.0.0.1:17815/rmt' failed: Could not decode a text frame as UTF-8.
9WebSocketConnection.js:54 WebSocket connection to 'ws://127.0.0.1:17815/rmt' failed: Could not decode a text frame as UTF-8.
```

On the WebSocketConnection.js file line 54:
		this.Socket = new WebSocket(address);

This error are reported by chrome:
```
WebSocket connection to 'ws://127.0.0.1:17815/rmt' failed: Could not decode a text frame as UTF-8.
WebSocket connection to 'ws://127.0.0.1:17815/rmt' failed: Invalid frame header
```

Any think I could test to track this issue ?

I wonder if I have too many marks, as I have changed my current profiller marks to call remotery...

**Comment by dwilliamson** [comment] 2015-02-03 10:54
Is there any way you can quickly change your code to only submit one profile mark? I'll take a quick look and see if there are any buffer limits in the send code.

**Comment by ulanda** [comment] 2015-02-03 10:56
yes I can do that, but in fact with an "idle" application that does almost nothing, it works fine.

**Comment by dwilliamson** [comment] 2015-02-03 10:58
Are you able to build and run the sample?

**Comment by dwilliamson** [comment] 2015-02-03 11:06
There are no buffer limits in the JSON serialisation code, I'll check and see if there's a bug in the websocket send code.

Do any of your sample names use unicode characters?

**Comment by dwilliamson** [comment] 2015-02-03 11:08
Can you breakpoint this line https://github.com/Celtoys/Remotery/blob/master/lib/Remotery.c#L3767 and post the contents of ``rmt->json_buf->data`` ? It should generally be a null-terminated string.

**Comment by ulanda** [comment] 2015-02-03 11:15
I build de sample and ran it, BUT I saw some unexpected behabiour, the log of the sample shows much more "end profile" than "start profile" lines.

**Comment by dwilliamson** [comment] 2015-02-03 11:17
I believe that's expected behaviour as the sample is an extreme stress-test of sending many frames as quickly as possible. Remotery won't block when its circular queue is full, it will just discard your frame's data or whatever text you've logged.

**Comment by dwilliamson** [comment] 2015-02-03 11:18
For your own sampling, can you also put a breakpoint on line https://github.com/Celtoys/Remotery/blob/master/lib/Remotery.c#L2508 and see if it triggers? Let me know the value of the ``length`` parameter.

**Comment by ulanda** [comment] 2015-02-03 11:21
Taht doent triger, the max I have seen is 0x00005180

**Comment by dwilliamson** [comment] 2015-02-03 11:22
OK, not too big then. What does ``rmt->json_buf->data`` look like?

**Comment by ulanda** [comment] 2015-02-03 11:26
{"id":"SAMPLES","thread_name":"Karisma","nb_samples":189,"sample_digest":937154801,"samples":[{"name":"SAL_APP_UPDATE","id":3736292808,"colour":"#cff87f","us_start":15265608,"us_length":16801,"children":[{"name":"KRT_UPDATE","id":1054384497,"colour":"#5b5ecf","us_start":15265609,"us_length":16800,"children":[{"name":"KRT_APP_UPDATE_INPUT","id":2255828864,"colour":"#4cb79b","us_start":15265611,"us_length":1},{"name":"KRT_APP_UPDATE_SCHEDULER","id":369002019,"colour":"#76acff","us_start":15265613,"us_length":16796,"children":[{"name":"GUI_UPDATE","id":3309669914,"colour":"#e5fc98","us_start":15265615,"us_length":1,"children":[{"name":"GUI_LAYOUT","id":1460567193,"colour":"#ddfbf4","us_start":15265616,"us_length":0}]},{"name":"GUI_RENDER","id":2895415934,"colour":"#fbec8d","us_start":15265618,"us_length":0},{"name":"GFX_SCENE_UPDATE","id":1772456651,"colour":"#ffec9e","us_start":15265619,"us_length":9,"children":[{"name":"GFX_SCENE_UPDATE_PREUPDATE","id":2941897851,"colour":"#fbffd9","us_start":15265620,"us_length":0},{"name":"GFX_SCENE_UPDATE_UPDATE","id":2673405630,"colour":"#ffffc9","us_start":15265621,"us_length":6,"children":[{"name":"GFX_SCENEGROUP_UPDATE","id":2667808942,"colour":"#fecc74","us_start":15265622,"us_length":2,"children":[{"name":"GFX_SCENEGROUP_UPDATE_LIST","id":2746585840,"colour":"#4f6d9f","us_start":15265623,"us_length":1}]},{"name":"GFX_SCENEGROUP_UPDATE","id":2667808929,"colour":"#5ecc74","us_start":15265625,"us_length":1,"children":[{"name":"GFX_SCENEGROUP_UPDATE_LIST","id":2743734534,"colour":"#a455ec","us_start":15265626,"us_length":0}]},{"name":"GFX_SCENEGROUP_UPDATE","id":2667808928,"colour":"#4ecc74","us_start":15265627,"us_length":0,"children":[{"name":"GFX_SCENEGROUP_UPDATE_LIST","id":2743731863,"colour":"#bda4ec","us_start":15265627,"us_length":0}]}]},{"name":"GFX_SCENE_UPDATE_POSTUPDATE","id":3059133593,"colour":"#ddfea9","us_start":15265628,"us_length":0}]},{"name":"GUT_RENDER_ONPRERENDER","id":218163445,"colour":"#9fcf44","us_start":15265635,"us_length":24,"children":[{"name":"GFX_DEBUGRENDER_CREATEPRIM","id":2635290466,"colour":"#6ab975","us_start":15265647,"us_length":2},{"name":"GFX_DEBUGRENDER_CREATEPRIM","id":2635290465,"colour":"#5ab975","us_start":15265650,"us_length":0},{"name":"GFX_DEBUGRENDER_CREATEPRIM","id":2635290464,"colour":"#4ab975","us_start":15265651,"us_length":1},{"name":"GFX_DEBUGRENDER_CREATEPRIM","id":2635290471,"colour":"#bab975","us_start":15265653,"us_length":0},{"name":"GFX_DEBUGRENDER_CREATEPRIM","id":2635290470,"colour":"#aab975","us_start":15265655,"us_length":0},{"name":"GFX_DEBUGRENDER_CREATEPRIM","id":2635290469,"colour":"#9ab975","us_start":15265656,"us_length":0},{"name":"GFX_DEBUGRENDER_CREATEPRIM","id":2635290468,"colour":"#8ab975","us_start":15265657,"us_length":0},{"name":"GFX_DEBUGRENDER_CREATEPRIM","id":2635290475,"colour":"#fab975","us_start":15265658,"us_length":1}]},{"name":"GFX_DEFAULTRS_CULLING","id":2010787757,"colour":"#fef6ef","us_start":15265669,"us_length":10,"children":[{"name":"GFX_CULLPHASE_EXECUTE","id":2622153656,"colour":"#cf7fe8","us_start":15265670,"us_length":5,"children":[{"name":"GFX_SPATIAL_UPDATE","id":1759563135,"colour":"#fbff4f","us_start":15265671,"us_length":1,"children":[{"name":"GFX_SPATIAL_UPDATE_ITEMS","id":1439420621,"colour":"#ff4fff","us_start":15265671,"us_length":1,"children":[{"name":"PHY_COL_VOLTREE_UPDATE_ITEM","id":1172460443,"colour":"#fd796f","us_start":15265672,"us_length":0}]}]}]},{"name":"GFX_OCCLUSIONPHASE_EXECUTE","id":2126631614,"colour":"#ff6f5f","us_start":15265675,"us_length":4,"children":[{"name":"GFX_OCCLUSIONPHASE_GATHER","id":3145783377,"colour":"#59cf4c","us_start":15265676,"us_length":0},{"name":"GFX_OCCLUSIONPHASE_OPTIMIZE","id":3167354480,"colour":"#4bffdf","us_start":15265676,"us_length":1},{"name":"GFX_OCCLUSIONPHASE_APPLY","id":1914943488,"colour":"#44cf76","us_start":15265677,"us_length":0}]}]},{"name":"GFX_DEFAULTRS_DRAW","id":1207051139,"colour":"#7c766f","us_start":15265679,"us_length":534,"children":[{"name":"GFX_DEBUGRENDER_CREATEPRIM","id":3837392557,"colour":"#feafdf","us_start":15265681,"us_length":0},{"name":"GFX_DEBUGRENDER_CREATEPRIM","id":3837392546,"colour":"#6eafdf","us_start":15265682,"us_length":1},{"name":"GFX_DEBUGRENDER_CREATEPRIM","id":3837392547,"colour":"#7eafdf","us_start":15265683,"us_length":7},{"name":"GFX_DEBUGRENDER_CREATEPRIM","id":3837392544,"colour":"#4eafdf","us_start":15265691,"us_length":4},{"name":"GFX_DEBUGRENDER_CREATEPRIM","id":3837392545,"colour":"#5eafdf","us_start":15265696,"us_length":0},{"name":"GFX_DEFAULTRENDERER_LIGHTING","id":531694350,"colour":"#f4745f","us_start":15265697,"us_length":1},{"name":"GFX_SHADOWMAPPHASE_EXECUTE","id":1182640662,"colour":"#a5eefb","us_start":15265702,"us_length":113,"children":[{"name":"GFX_RENDER_PRECOMMIT","id":3591296021,"colour":"#958ff4","us_start":15265771,"us_length":0},{"name":"GAL_GEOBATCHER_SORT","id":1799913145,"colour":"#dffbc8","us_start":15265773,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":3821469217,"colour":"#56ffaf","us_start":15265797,"us_length":15}]},{"name":"GFX_DEFAULTRENDERER_REFLECTOR","id":1456082512,"colour":"#49f4ef","us_start":15265816,"us_length":0},{"name":"GFX_DEFAULTRENDERER_RENDER","id":3392540402,"colour":"#6ff4a7","us_start":15265817,"us_length":395,"children":[{"name":"GFX_RENDER_PRECOMMIT","id":1435288420,"colour":"#8a7ffc","us_start":15265834,"us_length":1},{"name":"GAL_GEOBATCHER_SORT","id":1617002750,"colour":"#ff4c5a","us_start":15265865,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976312,"colour":"#cb4f5f","us_start":15265865,"us_length":26},{"name":"GFX_RENDER_PRECOMMIT","id":1435288425,"colour":"#da7ffc","us_start":15265893,"us_length":0},{"name":"GAL_GEOBATCHER_SORT","id":1617002747,"colour":"#ff4c5a","us_start":15265895,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976317,"colour":"#fb4f5f","us_start":15265896,"us_length":7},{"name":"GAL_GEOBATCHER_SORT","id":1617002757,"colour":"#945c5a","us_start":15265968,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976319,"colour":"#fb4f5f","us_start":15265968,"us_length":31},{"name":"GAL_GEOBATCHER_SORT","id":1617002759,"colour":"#b45c5a","us_start":15266028,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976305,"colour":"#5b4f5f","us_start":15266029,"us_length":10},{"name":"GAL_GEOBATCHER_SORT","id":1617002753,"colour":"#545c5a","us_start":15266044,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976307,"colour":"#7b4f5f","us_start":15266045,"us_length":11},{"name":"GAL_GEOBATCHER_SORT","id":1617002755,"colour":"#745c5a","us_start":15266060,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976309,"colour":"#9b4f5f","us_start":15266061,"us_length":6},{"name":"GAL_GEOBATCHER_SORT","id":1617002765,"colour":"#f45c5a","us_start":15266072,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976311,"colour":"#bb4f5f","us_start":15266073,"us_length":4},{"name":"GAL_GEOBATCHER_SORT","id":1617002767,"colour":"#f45c5a","us_start":15266082,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976297,"colour":"#da4f5f","us_start":15266082,"us_length":7},{"name":"GAL_GEOBATCHER_SORT","id":1617002761,"colour":"#d45c5a","us_start":15266092,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976299,"colour":"#fa4f5f","us_start":15266093,"us_length":3},{"name":"GAL_GEOBATCHER_SORT","id":1617002763,"colour":"#f45c5a","us_start":15266098,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976301,"colour":"#fa4f5f","us_start":15266099,"us_length":4},{"name":"GAL_GEOBATCHER_SORT","id":1617002773,"colour":"#955c5a","us_start":15266105,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976303,"colour":"#fa4f5f","us_start":15266106,"us_length":3},{"name":"GAL_GEOBATCHER_SORT","id":1617002775,"colour":"#b55c5a","us_start":15266111,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976289,"colour":"#5a4f5f","us_start":15266111,"us_length":4},{"name":"GAL_GEOBATCHER_SORT","id":1617002769,"colour":"#555c5a","us_start":15266117,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976291,"colour":"#7a4f5f","us_start":15266118,"us_length":2},{"name":"GAL_GEOBATCHER_SORT","id":1617002771,"colour":"#755c5a","us_start":15266122,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976293,"colour":"#9a4f5f","us_start":15266123,"us_length":3},{"name":"GAL_GEOBATCHER_SORT","id":1617002781,"colour":"#f55c5a","us_start":15266129,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976295,"colour":"#ba4f5f","us_start":15266129,"us_length":5},{"name":"GAL_GEOBATCHER_SORT","id":1617002783,"colour":"#f55c5a","us_start":15266138,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976089,"colour":"#ddff5f","us_start":15266138,"us_length":4},{"name":"GAL_GEOBATCHER_SORT","id":1617002777,"colour":"#d55c5a","us_start":15266149,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976091,"colour":"#fdff5f","us_start":15266150,"us_length":6},{"name":"GAL_GEOBATCHER_SORT","id":1617002779,"colour":"#f55c5a","us_start":15266159,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976093,"colour":"#fdff5f","us_start":15266160,"us_length":3},{"name":"GAL_GEOBATCHER_SORT","id":1617002789,"colour":"#965c5a","us_start":15266165,"us_length":1},{"name":"GAL_GEOBATCHER_COMMIT","id":147976095,"colour":"#fdff5f","us_start":15266167,"us_length":3},{"name":"GFX_RENDER_PRECOMMIT","id":1435288396,"colour":"#f87ffc","us_start":15266175,"us_length":0},{"name":"GAL_GEOBATCHER_SORT","id":1617002790,"colour":"#a65c5a","us_start":15266189,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976080,"colour":"#4dff5f","us_start":15266190,"us_length":11},{"name":"GFX_RENDER_PRECOMMIT","id":1435288369,"colour":"#577ffc","us_start":15266202,"us_length":1},{"name":"GAL_GEOBATCHER_SORT","id":1617002787,"colour":"#765c5a","us_start":15266205,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":147976085,"colour":"#9dff5f","us_start":15266206,"us_length":6}]}]},{"name":"GAL_GEOBATCHER_SORT","id":525827239,"colour":"#befbb9","us_start":15266282,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":642288449,"colour":"#58fcc8","us_start":15266283,"us_length":13},{"name":"GAL_GEOBATCHER_SORT","id":525827241,"colour":"#defbb9","us_start":15266313,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":642288451,"colour":"#78fcc8","us_start":15266313,"us_length":8},{"name":"GAL_GEOBATCHER_SORT","id":525827243,"colour":"#fefbb9","us_start":15266332,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":642288461,"colour":"#f8fcc8","us_start":15266333,"us_length":6},{"name":"GAL_GEOBATCHER_SORT","id":525827245,"colour":"#fefbb9","us_start":15266350,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":642288463,"colour":"#f8fcc8","us_start":15266351,"us_length":5},{"name":"GAL_GEOBATCHER_SORT","id":525827247,"colour":"#fefbb9","us_start":15266367,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":642288457,"colour":"#d8fcc8","us_start":15266367,"us_length":6},{"name":"GAL_GEOBATCHER_SORT","id":525827249,"colour":"#5ffbb9","us_start":15266384,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":642288459,"colour":"#f8fcc8","us_start":15266384,"us_length":8},{"name":"GAL_GEOBATCHER_SORT","id":525827251,"colour":"#7ffbb9","us_start":15266403,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":642288501,"colour":"#9bfcc8","us_start":15266403,"us_length":7},{"name":"GAL_GEOBATCHER_SORT","id":525827253,"colour":"#9ffbb9","us_start":15266420,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":642288503,"colour":"#bbfcc8","us_start":15266421,"us_length":7},{"name":"GAL_GEOBATCHER_SORT","id":525827255,"colour":"#bffbb9","us_start":15266441,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":642288497,"colour":"#5bfcc8","us_start":15266441,"us_length":6},{"name":"GAL_GEOBATCHER_SORT","id":525827257,"colour":"#dffbb9","us_start":15266457,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":642288499,"colour":"#7bfcc8","us_start":15266458,"us_length":5},{"name":"GAL_GEOBATCHER_SORT","id":525827259,"colour":"#fffbb9","us_start":15266473,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":642288509,"colour":"#fbfcc8","us_start":15266473,"us_length":5},{"name":"GAL_GEOBATCHER_SORT","id":525827261,"colour":"#fffbb9","us_start":15266491,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":642288511,"colour":"#fbfcc8","us_start":15266491,"us_length":8},{"name":"GAL_GEOBATCHER_SORT","id":525827263,"colour":"#fffbb9","us_start":15266509,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":642288505,"colour":"#dbfcc8","us_start":15266510,"us_length":6},{"name":"GAL_GEOBATCHER_SORT","id":525827201,"colour":"#5cfbb9","us_start":15266526,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":642288507,"colour":"#fbfcc8","us_start":15266526,"us_length":6},{"name":"GAL_GEOBATCHER_SORT","id":525827203,"colour":"#7cfbb9","us_start":15266545,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":642288485,"colour":"#9afcc8","us_start":15266545,"us_length":9},{"name":"GAL_GEOBATCHER_SORT","id":525827205,"colour":"#9cfbb9","us_start":15266569,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":642288487,"colour":"#bafcc8","us_start":15266570,"us_length":9},{"name":"GFX_DEBUGRENDER_RENDER","id":291952283,"colour":"#fdafaa","us_start":15266582,"us_length":54,"children":[{"name":"GAL_GEOBATCHER_SORT","id":3780336669,"colour":"#f5f979","us_start":15266593,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":1119394035,"colour":"#7fcdcf","us_start":15266594,"us_length":21},{"name":"GAL_GEOBATCHER_SORT","id":3780336659,"colour":"#75f979","us_start":15266619,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":1119394033,"colour":"#5fcdcf","us_start":15266620,"us_length":6},{"name":"GAL_GEOBATCHER_SORT","id":3780336657,"colour":"#55f979","us_start":15266629,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":1119395599,"colour":"#f4fdcf","us_start":15266630,"us_length":3},{"name":"GFX_DEBUGRENDER_RESET","id":735450459,"colour":"#f995af","us_start":15266635,"us_length":1}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952282,"colour":"#edafaa","us_start":15266638,"us_length":0,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":735470896,"colour":"#479aaf","us_start":15266638,"us_length":0}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952281,"colour":"#ddafaa","us_start":15266639,"us_length":1,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":735458915,"colour":"#7aa7af","us_start":15266640,"us_length":0}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952280,"colour":"#cdafaa","us_start":15266641,"us_length":1,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":735446610,"colour":"#69a4af","us_start":15266642,"us_length":0}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952263,"colour":"#bcafaa","us_start":15266643,"us_length":1,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":679230784,"colour":"#48f7fb","us_start":15266644,"us_length":0}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952262,"colour":"#acafaa","us_start":15266645,"us_length":1,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":679226545,"colour":"#5ff6fb","us_start":15266646,"us_length":0}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952261,"colour":"#9cafaa","us_start":15266647,"us_length":2,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":679222370,"colour":"#6af5fb","us_start":15266648,"us_length":0}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952260,"colour":"#8cafaa","us_start":15266649,"us_length":2,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":679218387,"colour":"#7ff4fb","us_start":15266651,"us_length":0}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952259,"colour":"#7cafaa","us_start":15266652,"us_length":1,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":679279171,"colour":"#78effb","us_start":15266653,"us_length":0}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952258,"colour":"#6cafaa","us_start":15266654,"us_length":0,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":679275058,"colour":"#67effb","us_start":15266654,"us_length":0}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952257,"colour":"#5cafaa","us_start":15266655,"us_length":1,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":679271009,"colour":"#5aeffb","us_start":15266656,"us_length":0}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952256,"colour":"#4cafaa","us_start":15266657,"us_length":1,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":679266896,"colour":"#49effb","us_start":15266658,"us_length":0}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952271,"colour":"#fcafaa","us_start":15266659,"us_length":0,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":679197768,"colour":"#c8fffb","us_start":15266659,"us_length":0}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952270,"colour":"#fcafaa","us_start":15266660,"us_length":1,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":679193529,"colour":"#dffefb","us_start":15266661,"us_length":0}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952269,"colour":"#fcafaa","us_start":15266662,"us_length":0,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":679189610,"colour":"#eafdfb","us_start":15266662,"us_length":0}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952268,"colour":"#fcafaa","us_start":15266663,"us_length":1,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":679185627,"colour":"#fffcfb","us_start":15266663,"us_length":1}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952267,"colour":"#fcafaa","us_start":15266664,"us_length":1,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":679247180,"colour":"#f8fbfb","us_start":15266665,"us_length":0}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952266,"colour":"#ecafaa","us_start":15266666,"us_length":5,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":679243069,"colour":"#f7fafb","us_start":15266671,"us_length":0}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952265,"colour":"#dcafaa","us_start":15266672,"us_length":1,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":679239278,"colour":"#faf9fb","us_start":15266673,"us_length":0}]},{"name":"GFX_SPRITEBATCH_RENDER","id":497298781,"colour":"#f9f68e","us_start":15266675,"us_length":0},{"name":"GFX_DEBUGRENDER_RENDER","id":291952375,"colour":"#bfafaa","us_start":15266675,"us_length":2,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":735361823,"colour":"#f5ff8f","us_start":15266677,"us_length":0}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952374,"colour":"#afafaa","us_start":15266678,"us_length":1,"children":[{"name":"GFX_DEBUGRENDER_RESET","id":735333006,"colour":"#fce88f","us_start":15266679,"us_length":0}]},{"name":"GFX_DEBUGRENDER_RENDER","id":291952373,"colour":"#9fafaa","us_start":15266681,"us_length":71,"children":[{"name":"GAL_GEOBATCHER_SORT","id":3785552769,"colour":"#5c7f6e","us_start":15266694,"us_length":1},{"name":"GAL_GEOBATCHER_COMMIT","id":1119243881,"colour":"#daf8af","us_start":15266696,"us_length":9},{"name":"GAL_GEOBATCHER_SORT","id":3785552771,"colour":"#7c7f6e","us_start":15266708,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":1119243883,"colour":"#faf8af","us_start":15266709,"us_length":6},{"name":"GAL_GEOBATCHER_SORT","id":3785552797,"colour":"#fd7f6e","us_start":15266718,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":1119243885,"colour":"#faf8af","us_start":15266718,"us_length":4},{"name":"GAL_GEOBATCHER_SORT","id":3785552799,"colour":"#fd7f6e","us_start":15266725,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":1119243887,"colour":"#faf8af","us_start":15266726,"us_length":15},{"name":"GAL_GEOBATCHER_SORT","id":3785552793,"colour":"#dd7f6e","us_start":15266744,"us_length":0},{"name":"GAL_GEOBATCHER_COMMIT","id":1119243873,"colour":"#5af8af","us_start":15266744,"us_length":5},{"name":"GFX_DEBUGRENDER_RESET","id":735337015,"colour":"#b7e98f","us_start":15266751,"us_length":1}]},{"name":"GFX_SPRITEBATCH_CLEAR","id":1520836952,"colour":"#c956ae","us_start":15282405,"us_length":0},{"name":"KRT_APP_UPDATE","id":427762308,"colour":"#8c66fb","us_start":15282409,"us_length":0}]}]}]}]}

**Comment by ulanda** [comment] 2015-02-03 11:27
I passed it trow JSLINT ad seems fine...

**Comment by ulanda** [comment] 2015-02-03 11:29
I think if say me how to log the websocket side may be we get a clue... 
Do you have any detection of "unpaired marks"?

**Comment by dwilliamson** [comment] 2015-02-03 11:30
No that's all valid JSON. Can you verify that this is the data that is getting sent to the browser? The contents of ``data`` on line https://github.com/Celtoys/Remotery/blob/master/lib/Remotery.c#L2475 should match what you read from the buffer above.

**Comment by dwilliamson** [comment] 2015-02-03 11:32
All the names look valid, too. There are a lot of samples, more than I've tested it with.

I'll add loads to my own and see what happens.

**Comment by dwilliamson** [comment] 2015-02-03 11:35
OK, I can repro this problem on my machine.

**Comment by ulanda** [comment] 2015-02-03 11:39
great! do you need more help? If you find a fix, I can test it again, this is ust an small "debug test" the complete frame probably is 100x this...

**Comment by dwilliamson** [comment] 2015-02-03 11:40
There are 189 samples in the data you sent me - do you mean that your real app will send 18900 samples?

**Comment by ulanda** [comment] 2015-02-03 11:45
may be not that much bat probably 5k-10k is possible, I used to have "accumulated" mark that we used to count on allocations, that while loading ca go up fast.
Also with may objects/drawcalls that can go up easy,

I see that you send allways full marks, I think you could use the hash to send to the client the associated mark info to the client and per frame sending only the mark id + counters.

**Comment by dwilliamson** [comment] 2015-02-03 11:57
> may be not that much bat probably 5k-10k is possible, I used to have "accumulated" mark that we used to count on allocations, that while loading ca go up fast.
> Also with may objects/drawcalls that can go up easy,

I doubt the viewer in its current state will handle rendering that number of samples in real-time. I'm sure there are some optimisations we can do to filter stuff out but it might be slow once this works.

I have plans for "cumulative" samples such as "GAL_GEOBATCHER_SORT" that allow you to some the cost of the same sample name over an entire frame and that will reduce what you view massively.

> I see that you send allways full marks, I think you could use the hash to send to the client the associated mark info to the client and per frame sending only the mark id + counters.

That would be nice to do but that's a bit of extra complexity:

* The C code would have to track known names in a dynamic buffer to see whether it needs to send it to the viewer or not. This needs to be fast to lookup.
* Or somehow introduce more state that the user needs to record that stores whether the name has been sent (even an integer stating the last session ID so that it gets automatically resent on disconnect). Currently this is limited to the cached sample hash.
* On connect/disconnect this all needs to be flushed.
* The viewer needs a map from ID to name. This should actually be straight-forward.

So, yeah... it could improve performance for the C code (no JSON encoding for strings required), cut down on network traffic (increasing performance for the OS stack and browser drivers) and the decode step in the viewer.

Worth opening a pull request but if that's not the problem here, it's not something I can work on soon :)

**Comment by dwilliamson** [comment] 2015-02-03 12:43
OK, I have this "solved" with some code that can go into an infinite loop but I understand the problem.

The websocket frame is being sent in with two calls: one to send the frame header, the other to send the frame data:

* Pass 1: Send frame header (max 10 bytes)
* Pass 1: Send frame data (a large amount, say >10k bytes)
* Pass 2: Send frame header (max 10 bytes)
* Pass 2: Send frame data - FAILS with timeout

This failure is not fatal but the server's handling of it causes two things:

* The browser receives an incomplete frame without data and complains.
* The server continues sending the next frame incorrectly.

It might take a bit longer to come up with a solution that's good for all scenarios.

**Comment by dwilliamson** [comment] 2015-02-03 12:46
Either way, once this is fixed it looks like Remotery gets caught up with lots of network congestion. I'm not sure why this is as I've sent entire frame buffers over websockets before, but we'll see...

**Comment by dwilliamson** [comment] 2015-02-03 13:25
I believe I have this fixed the correct way. Can you pull latest code and test it for me?

**Comment by ulanda** [comment] 2015-02-03 13:53
yep, give me 30 min

**Comment by ulanda** [comment] 2015-02-03 14:10
It works, I tested with 2000 timeout  yesterday :) but I see that was not the only problem...

I'll do more depth testing, thanks!

Just one more question, apart than the color is there a way to "sync" the hierarchical tree view with the time bars? or a tooltip for the bars?

Any way it look really nice...

**Comment by dwilliamson** [comment] 2015-02-03 14:55
Great, I'll close this up. Thanks for the report.

I have plans to add text to the timeline view, as well as sample selection/tool tips very soon.

**Closed** 2015-02-03 14:55 UTC
